name: modular105
favicon: null
layout_spectrum: 0.24103079992346466
typography_spectrum: 0.7779958643950522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12898432090878487
  lightness: 0.7693121873307973
  saturation: 0.5571891269646585
  rhythmicContrast: 0.07116903061978519
purpose: []
